### ISSUE TITLE
Despliegue con Docker

### ISSUE THREAD

**Issue by vk496** [RITSI/MapaTasas#37]
Buenas,

Estoy intentando desplegar el Mapa de Tasas. Al igual que la última vez, me está costando conseguirlo. Es por ello que estoy intentando llevarlo en Docker.

Hasta ahora, tengo esto

```
FROM ubuntu:16.10

#RUN apt-get update

## ENVRIOMENT
RUN apt-get update
RUN apt-get install -y -q libjpeg8-dev zlib1g-dev python-pip nodejs-legacy npm git
RUN echo '{ "allow_root": true }' > /root/.bowerrc

## 
COPY . /MapaTasas
WORKDIR /MapaTasas

## Python dependencies
RUN pip install --upgrade pip 
RUN npm install -g bower topojson ogr2ogr
RUN pip install -r requirements.txt
RUN bower install
```

Llegado a este punto, no puedo continuar. Para empezar, me falla el siguiente comando:

```bash
root@733bccafc1b5:/MapaTasas# python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/MapaTasas/tasasrest/settings.py", line 58
SyntaxError: Non-ASCII character '\xc3' in file /MapaTasas/tasasrest/settings.py on line 58, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

Se podría arreglar añadiendo `# -*- coding: utf-8 -*- ` al principio (no sé por que ocurre esto la verdad). Sin embargo, sigo atascandome aquí, sin saber como continuar...

```bash
root@733bccafc1b5:/MapaTasas# python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 195, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 16, in <module>
    from django.db.migrations.autodetector import MigrationAutodetector
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/autodetector.py", line 13, in <module>
    from django.db.migrations.questioner import MigrationQuestioner
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/questioner.py", line 12, in <module>
    from .loader import MigrationLoader
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 10, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 12, in <module>
    class MigrationRecorder(object):
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 26, in MigrationRecorder
    class Migration(models.Model):
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 27, in Migration
    app = models.CharField(max_length=255)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 1072, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 166, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 120, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

Con un poco de suerte, sería una forma mucho mas cómoda de desarrollar

**Comment by martinarroyo** [comment]
El primer error se debe a que estás utilizando python 2 en vez de python 3. Creo que con 

```
FROM ubuntu:16.10

#RUN apt-get update

## ENVRIOMENT
RUN apt-get update
RUN apt-get install -y -q libjpeg8-dev zlib1g-dev python3-pip nodejs-legacy npm git
RUN echo '{ "allow_root": true }' > /root/.bowerrc

## 
COPY . /MapaTasas
WORKDIR /MapaTasas

## Python dependencies
RUN pip3 install --upgrade pip 
RUN npm install -g bower topojson ogr2ogr
RUN pip3 install -r requirements.txt
RUN bower install
```

debería funcionar.

El segundo error se debe a que la clave secreta que se utiliza para general los hashes de las contraseñas y otros valores no se incluye en el repositorio por razones de seguridad. En la [documentación](https://github.com/RITSI/MapaTasas/blob/master/docs/index.md) puedes encontrar una guía de todos pasos a realizar para configurar la aplicación.

**Comment by vk496** [comment]
Hola, gracias!

He añadido un pequeño cambio para SECRET_KEY (fa48e30d9acd7404bfb8f126afdebf189ab7310b) y ahora todo parece funcionar:

```bash
FROM ubuntu:16.10

## ENVRIOMENT
RUN apt-get update
RUN apt-get install -y -q libjpeg8-dev zlib1g-dev python3-pip nodejs-legacy npm git
RUN echo '{ "allow_root": true }' > /root/.bowerrc

## Python dependencies
RUN pip3 install --upgrade pip 
RUN npm install -g bower topojson ogr2ogr

## Project
COPY . /MapaTasas
WORKDIR /MapaTasas
RUN pip3 install -r requirements.txt
RUN bower install

## Desplegar
ENV SECRET_KEY no-secret-key #Set a secure secret key fro production!

RUN python3 manage.py migrate # Creación de la base de datos y definición de tablas
RUN python3 manage.py collectstatic --noinput # Copia los ficheros estáticos de todas las aplicaciones a un directorio común
RUN python3 manage.py test # Ejecuta los tests unitarios
RUN python3 manage.py createsuperuser # Crea un superusuario
RUN python3 manage.py check --deploy # Comprueba que los ajustes definidos son apropiados para una configuración de despliegue

EXPOSE 8000

#CMD ["python3", "manage.py runserver 0.0.0.0:8000"]
```

Lo único que me falla ahora son los tests unitarios. No sé si se deben a que les falta alguna dependencia, el unis.json con datos o realmente es un problema de código.

```bash
Step 14/18 : RUN python3 manage.py test # Ejecuta los tests unitarios
 ---> Running in d49b4739791e
nosetests --with-coverage --cover-html --cover-package=tasas,mapa --verbosity=1
Creating test database for alias 'default'...
Destroying test database for alias 'default'...
EE
======================================================================                                                                                      
ERROR: test_invalid_curso (mapa.tests.TestReporteModel)                                                                                                     
----------------------------------------------------------------------                                                                                      
Traceback (most recent call last):                                                                                                                          
  File "/usr/local/lib/python3.5/dist-packages/mock/mock.py", line 1297, in patched                                                                         
    arg = patching.__enter__()                                                                                                                              
  File "/usr/local/lib/python3.5/dist-packages/mock/mock.py", line 1369, in __enter__                                                                       
    original, local = self.get_original()                                                                                                                   
  File "/usr/local/lib/python3.5/dist-packages/mock/mock.py", line 1343, in get_original                                                                    
    "%s does not have the attribute %r" % (target, name)                                                                                                    
AttributeError: <module 'tasas.models' from '/MapaTasas/tasas/models.py'> does not have the attribute 'datetime'                                            

======================================================================                                                                                      
ERROR: Failure: ImportError (cannot import name 'CursoValidator')                                                                                           
----------------------------------------------------------------------                                                                                      
Traceback (most recent call last):                                                                                                                          
  File "/usr/local/lib/python3.5/dist-packages/nose/failure.py", line 39, in runTest                                                                        
    raise self.exc_val.with_traceback(self.tb)                                                                                                              
  File "/usr/local/lib/python3.5/dist-packages/nose/loader.py", line 418, in loadTestsFromName                                                              
    addr.filename, addr.module)                                                                                                                             
  File "/usr/local/lib/python3.5/dist-packages/nose/importer.py", line 47, in importFromPath                                                                
    return self.importFromDir(dir_path, fqname)                                                                                                             
  File "/usr/local/lib/python3.5/dist-packages/nose/importer.py", line 94, in importFromDir                                                                 
    mod = load_module(part_fqname, fh, filename, desc)                                                                                                      
  File "/usr/lib/python3.5/imp.py", line 234, in load_module                                                                                                
    return load_source(name, filename, file)                                                                                                                
  File "/usr/lib/python3.5/imp.py", line 172, in load_source                                                                                                
    module = _load(spec)                                                                                                                                    
  File "<frozen importlib._bootstrap>", line 693, in _load                                                                                                  
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked                                                                                         
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module                                                                                   
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed                                                                              
  File "/MapaTasas/tasas/tests.py", line 5, in <module>                                                                                                     
    from .models import Universidad, Tasa, CursoValidator, get_current_curso, curso_choices                                                                 
ImportError: cannot import name 'CursoValidator'                                                                                                            

Name                                          Stmts   Miss  Cover   Missing                                                                                 
---------------------------------------------------------------------------                                                                                 
mapa.py                                           0      0   100%                                                                                           
mapa/admin.py                                     5      5     0%   1-8                                                                                     
mapa/migrations/0001_initial.py                   8      0   100%                                                                                           
mapa/migrations/0002_auto_20160306_1703.py        6      0   100%                                                                                           
mapa/migrations/0003_auto_20160306_1711.py        7      0   100%   
mapa/migrations.py                                0      0   100%   
mapa/models.py                                   16     16     0%   1-32
tasas.py                                          0      0   100%   
tasas/admin.py                                    5      5     0%   1-9
tasas/api.py                                      0      0   100%   
tasas/management/commands.py                      0      0   100%   
tasas/management/commands/importar.py            97     77    21%   30-33, 37-44, 47-56, 59-62, 72-109, 118-126, 138, 141-164
tasas/migrations/0001_initial.py                  8      0   100%   
tasas/migrations/0002_auto_20160227_1902.py       5      0   100%   
tasas/migrations/0003_auto_20160227_2048.py       5      0   100%   
tasas/migrations/0004_auto_20160228_1421.py       8      0   100%   
tasas/migrations/0005_auto_20160228_1424.py       6      0   100%   
tasas/migrations/0006_auto_20160228_1427.py       6      0   100%   
tasas/migrations/0007_auto_20160229_2059.py       6      0   100%   
tasas/migrations/0008_auto_20160229_2102.py       5      0   100%   
tasas/migrations/0009_auto_20160301_1825.py       5      0   100%   
tasas/migrations/0010_auto_20160304_1825.py       7      0   100%   
tasas/migrations/0011_auto_20160304_1826.py       7      0   100%   
tasas/migrations/0012_auto_20160306_1444.py       5      0   100%   
tasas/migrations/0013_auto_20160306_1507.py       7      0   100%   
tasas/migrations/0014_auto_20160306_1723.py       5      0   100%   
tasas/migrations/0015_auto_20160904_1650.py       7      0   100%   
tasas/migrations/0016_auto_20160904_1653.py       6      0   100%   
tasas/migrations/0017_auto_20160904_1655.py       8      0   100%   
tasas/migrations/0018_auto_20160911_1718.py       6      0   100%   
tasas/migrations/0019_curso_actual.py             5      0   100%   
tasas/migrations/0020_auto_20161102_1103.py       6      0   100%   
tasas/migrations.py                               0      0   100%   
tasas/models.py                                 115    115     0%   1-228
tasas/provincias.py                               1      1     0%   1
---------------------------------------------------------------------------
TOTAL                                           383    219    43%   
----------------------------------------------------------------------
Ran 2 tests in 0.002s

FAILED (errors=2)
The command '/bin/sh -c python3 manage.py test # Ejecuta los tests unitarios' returned a non-zero code: 1
```

En caso de comentar la parte de los tests unitarios, se puede desplegar perfectamente con:
`$ docker build -t mapa-tasas .`
`$ docker run -it --rm -p 8000:8000 mapa-tasas python3 manage.py runserver 0.0.0.0:8000`

**Comment by vk496** [comment]
Creo que lo mejor es separarlo. Tener el docker solo para desplegar, teniendo los tests fuera del build para que cada uno lo ejecute por su cuenta.

**Comment by martinarroyo** [comment]
Creo que los tests están desfasados porque tuvimos que cambiar una cosa a la carrera, así que puedes desactivarlos por ahora.
